//! RFC 3389 comfort noise (payload type 13).
//!
//! We use the amplitude-only payload variant: one byte holding the noise
//! level in −dBov (0..=127). White noise is generated by a deterministic
//! xorshift generator so tests and runtime are reproducible.

use crate::error::{CodecError, Result};
use crate::traits::{CodecId, Decoder, Encoder, FormatInfo};

/// SDP descriptor for CN @ 8000 Hz.
pub const CN_INFO: FormatInfo = FormatInfo {
    id: CodecId::ComfortNoise,
    name: "CN",
    payload_type: 13,
    clock_rate: 8000,
    channels: 1,
    fmtp: None,
};

/// Encode an RMS level (0..32767) into the RFC 3389 one-byte payload.
///
/// Returns the noise level in −dBov, clamped to 0..=127.
pub fn encode_cn_payload(rms: i16) -> u8 {
    if rms <= 0 {
        return 127;
    }
    let db = -20.0 * (rms as f64 / 32_767.0).log10();
    db.round().clamp(0.0, 127.0) as u8
}

/// Decode a one-byte RFC 3389 payload back to a target RMS level.
pub fn decode_cn_payload(level_db: u8) -> i16 {
    if level_db >= 127 {
        return 0;
    }
    let rms = 32_767.0 * 10f64.powf(-(level_db as f64) / 20.0);
    rms.round().clamp(0.0, 32_767.0) as i16
}

/// Deterministic xorshift64* generator (no external dependency).
#[derive(Debug, Clone)]
pub struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    /// Create a generator from a non-zero seed (zero is remapped to 0x9E3779B97F4A7C15).
    pub fn new(seed: u64) -> XorShift64 {
        XorShift64 {
            state: if seed == 0 {
                0x9E37_79B9_7F4A_7C15
            } else {
                seed
            },
        }
    }

    /// Next raw u64.
    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.state = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    /// Next noise sample, uniform in [−1.0, 1.0) (RMS = 1/√3).
    pub fn next_unit(&mut self) -> f64 {
        // 53-bit uniform in [0,1).
        let u = (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64;
        u * 2.0 - 1.0
    }

    /// Next sample roughly uniform in [−32767, 32767].
    pub fn next_noise(&mut self) -> i16 {
        (self.next_unit() * 32_767.0).clamp(-32_767.0, 32_767.0) as i16
    }
}

/// Comfort-noise encoder: measures frame RMS and emits the 1-byte payload.
#[derive(Debug, Clone, Default)]
pub struct ComfortNoiseEncoder;

impl ComfortNoiseEncoder {
    /// Create a CN encoder.
    pub fn new() -> ComfortNoiseEncoder {
        ComfortNoiseEncoder
    }

    /// Compute frame RMS (clamped to i16 range).
    pub fn frame_rms(pcm: &[i16]) -> i16 {
        if pcm.is_empty() {
            return 0;
        }
        let sum: f64 = pcm.iter().map(|&s| (s as f64) * (s as f64)).sum();
        let rms = (sum / pcm.len() as f64).sqrt();
        rms.round().clamp(0.0, 32_767.0) as i16
    }
}

impl Encoder for ComfortNoiseEncoder {
    fn encode(&mut self, pcm: &[i16], out: &mut Vec<u8>) -> Result<usize> {
        out.push(encode_cn_payload(Self::frame_rms(pcm)));
        Ok(1)
    }

    fn sample_rate(&self) -> u32 {
        8000
    }

    fn channels(&self) -> u8 {
        1
    }

    fn frame_samples(&self) -> usize {
        160
    }

    fn reset(&mut self) {}
}

/// Comfort-noise decoder: synthesizes white noise at the payload level.
#[derive(Debug, Clone)]
pub struct ComfortNoiseDecoder {
    gen: XorShift64,
    last_level: u8,
}

impl ComfortNoiseDecoder {
    /// Create a CN decoder with a deterministic seed.
    pub fn new(seed: u64) -> ComfortNoiseDecoder {
        ComfortNoiseDecoder {
            gen: XorShift64::new(seed),
            last_level: 127,
        }
    }
}

impl Decoder for ComfortNoiseDecoder {
    fn decode(&mut self, data: &[u8], out: &mut Vec<i16>) -> Result<usize> {
        if data.len() != 1 {
            return Err(CodecError::InvalidData(format!(
                "CN payload must be 1 byte, got {}",
                data.len()
            )));
        }
        self.last_level = data[0];
        self.conceal(out)
    }

    fn conceal(&mut self, out: &mut Vec<i16>) -> Result<usize> {
        let target_rms = decode_cn_payload(self.last_level) as f64;
        // Uniform noise in [−1,1] has RMS 1/√3; scale to target RMS.
        let src_rms = 1.0 / 3.0f64.sqrt();
        let g = if src_rms > 0.0 {
            target_rms / (src_rms * 32_767.0)
        } else {
            0.0
        };
        for _ in 0..160 {
            out.push((self.gen.next_unit() * 32_767.0 * g).clamp(-32_768.0, 32_767.0) as i16);
        }
        Ok(160)
    }

    fn sample_rate(&self) -> u32 {
        8000
    }

    fn channels(&self) -> u8 {
        1
    }

    fn frame_samples(&self) -> usize {
        160
    }

    fn reset(&mut self) {
        // keep generator continuity; level unchanged
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payload_roundtrip_within_1db() {
        for rms in [1i16, 10, 100, 1_000, 10_000, 32_767] {
            let b = encode_cn_payload(rms);
            let back = decode_cn_payload(b);
            let ratio = back as f64 / rms as f64;
            let err_db = 20.0 * ratio.abs().log10();
            assert!(
                err_db.abs() <= 1.0,
                "rms {rms} -> {b} dB -> {back} ({err_db} dB)"
            );
        }
    }

    #[test]
    fn special_levels() {
        assert_eq!(encode_cn_payload(0), 127);
        assert_eq!(encode_cn_payload(-5), 127);
        assert_eq!(decode_cn_payload(127), 0);
        assert_eq!(decode_cn_payload(0), 32_767);
    }

    #[test]
    fn generator_deterministic() {
        let mut a = XorShift64::new(42);
        let mut b = XorShift64::new(42);
        for _ in 0..1000 {
            assert_eq!(a.next_u64(), b.next_u64());
        }
        let mut z = XorShift64::new(0);
        assert_ne!(z.next_u64(), 0);
    }

    #[test]
    fn noise_bounded() {
        let mut g = XorShift64::new(7);
        for _ in 0..10_000 {
            let s = g.next_noise();
            assert!((-32_767..=32_767).contains(&s));
        }
    }

    #[test]
    fn rms_measurement() {
        assert_eq!(ComfortNoiseEncoder::frame_rms(&[]), 0);
        assert_eq!(ComfortNoiseEncoder::frame_rms(&[0; 160]), 0);
        let r = ComfortNoiseEncoder::frame_rms(&[16_000i16; 160]);
        assert_eq!(r, 16_000);
    }

    #[test]
    fn cn_decoder_synthesizes_level() {
        let mut d = ComfortNoiseDecoder::new(99);
        let payload = [encode_cn_payload(2_000)];
        let mut out = Vec::new();
        d.decode(&payload, &mut out).unwrap();
        assert_eq!(out.len(), 160);
        let rms = ComfortNoiseEncoder::frame_rms(&out);
        let err_db = 20.0 * (rms as f64 / 2_000.0).log10();
        assert!(
            err_db.abs() <= 3.0,
            "synthetic RMS {rms} not near 2000 ({err_db} dB)"
        );
    }

    #[test]
    fn cn_encoder_produces_one_byte() {
        let mut e = ComfortNoiseEncoder::new();
        let mut out = Vec::new();
        assert_eq!(e.encode(&[1_000i16; 160], &mut out).unwrap(), 1);
        assert_eq!(out.len(), 1);
    }

    #[test]
    fn cn_bad_payload() {
        let mut d = ComfortNoiseDecoder::new(1);
        let mut out = Vec::new();
        assert!(matches!(
            d.decode(&[1, 2], &mut out),
            Err(CodecError::InvalidData(_))
        ));
    }
}
