#![forbid(unsafe_code)]
//! # sip-tx — RFC 3261 transaction state machines
//!
//! Pure transaction-layer state machines (RFC 3261 §17). **No I/O, no async
//! runtime, no sockets, no threads.** The only dependency is [`sip-core`]
//! for the message types. Callers drive time and events:
//!
//! * feed wire events with [`TxEvent`] via [`ClientTx::on_event`]-style
//!   methods,
//! * poll [`next_deadline`](ClientInviteTx::next_deadline) and deliver
//!   [`TxEvent::Timeout`] when that instant passes (a fake clock in tests,
//!   a real timer in production),
//! * execute every returned [`TxAction`] — the state machines never touch
//!   the network themselves.
//!
//! Because all time enters through `now: Instant` parameters, every timer
//! transition is unit-testable with a hand-rolled fake clock.
//!
//! # Timers (RFC 3261 §17.1.1.2 / §17.1.2.2)
//!
//! Defaults per [`TimerConfig`]: T1 = 500 ms, T2 = 4 s, T4 = 5 s.
//! Derivations: Timer A/E/G start at T1 and double per fire (E/G capped at
//! T2); B/F/H = 64·T1; D = max(32 s, 64·T1); I/K = T4; J = 64·T1. Reliable
//! transports (TCP/TLS/WS/WSS) suppress the retransmission timers A/E/G and
//! collapse D/I/K to zero.
//!
//! # Transactions
//!
//! | Type | RFC section |
//! |------|-------------|
//! | [`ClientInviteTx`] | §17.1.1 |
//! | [`ClientNonInviteTx`] | §17.1.2 |
//! | [`ServerInviteTx`] | §17.2.1 |
//! | [`ServerNonInviteTx`] | §17.2.2 |
//!
//! Matching (RFC 3261 §17.1.3 / §17.2.3): responses match on top-Via
//! branch + sent-by + CSeq (method and number); an ACK for a 2xx is a
//! separate transaction and never matches the INVITE transaction state
//! machine; an ACK for a non-2xx final response is generated by
//! [`ClientInviteTx`] itself (§17.1.1) and matched by
//! [`ServerInviteTx`] via [`matching::ack_matches_invite`].

pub mod client;
pub mod matching;
pub mod server;

use sip_core::message::{Request, Response, SipMessage};
use std::time::{Duration, Instant};

pub use client::{build_non2xx_ack, ClientInviteTx, ClientNonInviteTx};
pub use matching::TxKey;
pub use server::{ServerInviteTx, ServerNonInviteTx};

#[cfg(test)]
mod tests;

/// Transaction-layer state (RFC 3261 §17). The RFC's `Confirmed` state is
/// represented as [`TxState::Completed`] with the ACK seen — see
/// [`ServerInviteTx::is_confirmed`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TxState {
    /// INVITE sent / request received, nothing passed yet.
    Trying,
    /// Provisional response seen on either side.
    Proceeding,
    /// Final response sent or received; waiting for ACK / cleanup.
    Completed,
    /// Terminal; a cleanup deadline may still be pending.
    Terminated,
}

/// Inputs to a transaction state machine. Every arrow of the RFC 3261
/// state diagrams is one `TxEvent` delivery.
#[derive(Debug, Clone)]
pub enum TxEvent {
    /// TU asks the transaction to send its stored request (client) or the
    /// staged response (server; stage it first with
    /// [`ServerInviteTx::stage`] / [`ServerNonInviteTx::stage`]).
    Send,
    /// The instant returned by `next_deadline()` has passed. The state
    /// machine disambiguates which timer fired (retransmit vs timeout vs
    /// cleanup) from its own deadlines.
    Timeout,
    /// Transport confirmed delivery of the request/response: stops the
    /// retransmission timers (A/E/G); timeout timers stay armed.
    Delivered,
    /// A response arrived from the wire (client transactions).
    Received(Response),
    /// A request arrived from the wire — original-request retransmissions
    /// and ACKs for server transactions.
    ReceivedRequest(Request),
    /// Transport reported a permanent failure.
    TransportError,
}

/// Outputs of a transaction state machine. The caller executes them in
/// order; the machines are pure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TxAction {
    /// Put this request on the wire (initial send, retransmission, or the
    /// ACK a client INVITE transaction generates for a non-2xx final).
    SendRequest(Request),
    /// Put this response on the wire (server transactions).
    SendResponse(Response),
    /// Hand this message up/down to the TU (e.g. a received response).
    PassToTu(SipMessage),
    /// Release the transaction (its state is or has become `Terminated`).
    DeleteTransaction,
}

/// RFC 3261 timer configuration. All durations are derivations of T1/T2/T4.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TimerConfig {
    /// T1 — RTT estimate (default 500 ms).
    pub t1: Duration,
    /// T2 — maximum retransmit interval for non-INVITE requests and
    /// INVITE/2xx responses (default 4 s).
    pub t2: Duration,
    /// T4 — time the network takes to clear messages (default 5 s).
    pub t4: Duration,
}

impl Default for TimerConfig {
    fn default() -> Self {
        TimerConfig {
            t1: Duration::from_millis(500),
            t2: Duration::from_secs(4),
            t4: Duration::from_secs(5),
        }
    }
}

impl TimerConfig {
    /// Timer B / F / H — 64·T1.
    pub fn timer_bfh(&self) -> Duration {
        self.t1 * 64
    }

    /// Timer D — at least 32 s (RFC 3261 §17.1.1.2).
    pub fn timer_d(&self) -> Duration {
        const MIN_D: Duration = Duration::from_secs(32);
        std::cmp::max(MIN_D, self.t1 * 64)
    }

    /// Timer J — 64·T1 (RFC 3261 §17.2.2).
    pub fn timer_j(&self) -> Duration {
        self.t1 * 64
    }
}

/// Transport reliability class for timer selection. sip-tx only needs the
/// reliable/unreliable distinction (RFC 3261 §17.1.1.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Transport {
    Udp,
    Tcp,
    Tls,
    Ws,
    Wss,
}

impl Transport {
    /// Reliable transports need no retransmission timers (A/E/G) and zero
    ///-duration D/I/K.
    pub fn is_reliable(self) -> bool {
        !matches!(self, Transport::Udp)
    }
}

/// `now + d`, saturating instead of panicking (transaction timers are the
/// only arithmetic; intervals are bounded by 64·T1 in practice).
pub(crate) fn add(now: Instant, d: Duration) -> Instant {
    now.checked_add(d).unwrap_or(now)
}

/// Earliest of two optional deadlines.
pub(crate) fn earliest(a: Option<Instant>, b: Option<Instant>) -> Option<Instant> {
    match (a, b) {
        (Some(x), Some(y)) => Some(std::cmp::min(x, y)),
        (Some(x), None) => Some(x),
        (None, y) => y,
    }
}
