//! SBC behavior tests: ACL, rate limiting, NAT latching, topology hiding.

use sbc::{Acl, Cidr, Sbc, SbcAction, SbcConfig};
use sip_core::builder::RequestBuilder;
use sip_core::message::Method;
use sip_core::uri::{SipUri, TransportKind};
use std::net::{IpAddr, Ipv4Addr, SocketAddr};

const PEER: SocketAddr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(203, 0, 113, 7)), 5060);
const INTERNAL: SocketAddr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)), 5060);

fn invite(user: &str, contact: &str) -> sip_core::Request {
    RequestBuilder::new(
        Method::Invite,
        SipUri::parse(&format!("sip:{user}@example.com")).unwrap(),
    )
    .via(TransportKind::Udp, "peer.example:5060", Some("z9hG4bKs1"))
    .from(&format!("<sip:{user}@example.com>;tag=s1"))
    .to(&format!("<sip:{user}@example.com>"))
    .call_id(Some("scall-1"))
    .cseq(1)
    .contact(&format!("<{contact}>"))
    .build()
}

fn config() -> SbcConfig {
    SbcConfig {
        acl: Acl::default(),
        rate: sbc::RateLimit {
            per_second: 1000.0,
            burst: 1000.0,
        },
        external: "sbc.voip-stack:5060".into(),
        internal_target: INTERNAL,
        topology_hiding: true,
    }
}

#[test]
fn acl_allows_and_denies() {
    let mut sbc = Sbc::new(config());
    // Default: everything allowed.
    let req = invite("alice", "sip:alice@203.0.113.7:5060");
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Relay(_)
    ));

    // Deny the peer's subnet.
    let mut cfg = config();
    cfg.acl.deny = vec![Cidr::v4(203, 0, 113, 0, 24)];
    let mut sbc = Sbc::new(cfg);
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));

    // Allow-list that excludes the peer.
    let mut cfg = config();
    cfg.acl.allow = vec![Cidr::v4(198, 51, 100, 0, 24)];
    let mut sbc = Sbc::new(cfg);
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));
}

#[test]
fn cidr_matching() {
    let net = Cidr::v4(10, 0, 0, 0, 8);
    assert!(net.contains("10.1.2.3".parse().unwrap()));
    assert!(!net.contains("11.0.0.1".parse().unwrap()));
    let single = Cidr::v4(1, 2, 3, 4, 32);
    assert!(single.contains("1.2.3.4".parse().unwrap()));
    assert!(!single.contains("1.2.3.5".parse().unwrap()));
    let zero = Cidr::v4(0, 0, 0, 0, 0);
    assert!(zero.contains("255.255.255.255".parse().unwrap()));
}

#[test]
fn rate_limit_enforced() {
    let mut cfg = config();
    cfg.rate = sbc::RateLimit {
        per_second: 1.0,
        burst: 3.0,
    };
    let mut sbc = Sbc::new(cfg);
    let req = invite("bob", "sip:bob@203.0.113.7:5060");
    for _ in 0..3 {
        assert!(matches!(
            sbc.process_request(&req, PEER),
            SbcAction::Relay(_)
        ));
    }
    // Bucket drained.
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));
}

#[test]
fn nat_latch_records_source() {
    let mut sbc = Sbc::new(config());
    let req = invite("carol", "sip:carol@203.0.113.7:5060");
    let _ = sbc.process_request(&req, PEER);
    let key = "sip:carol@203.0.113.7:5060";
    assert_eq!(sbc.latches().lookup(key), Some(PEER));
}

#[test]
fn topology_hiding_rewrites_call_id_and_contact() {
    let mut sbc = Sbc::new(config());
    let req = invite("dave", "sip:dave@10.0.0.1:5060");
    let hidden = match sbc.process_request(&req, PEER) {
        SbcAction::Relay(relayed) => {
            let cid = relayed.headers.call_id().unwrap().to_string();
            assert!(cid.starts_with("h-"), "call-id hidden: {cid}");
            assert!(!cid.contains("scall-1"));
            let contact = relayed.headers.get("Contact").unwrap();
            assert!(
                contact.contains("sbc.voip-stack:5060"),
                "contact rewritten: {contact}"
            );
            assert!(!contact.contains("10.0.0.1"));
            // rport marking added for NAT traversal.
            let via = relayed.headers.first_via().unwrap();
            assert!(via.rport.is_some());
            cid
        }
        _ => panic!("expected relay"),
    };

    // A response generated by the internal core echoes the HIDDEN id (the
    // core saw the rewritten request); it must leave with the peer's real id.
    let mut core_req = req.clone();
    core_req.headers.remove_all("Call-ID");
    core_req.headers.add("Call-ID", hidden.clone());
    let core_resp = sip_core::builder::respond_to(&core_req, 200, "OK", Vec::new(), None);
    let external = sbc.process_response(&core_resp);
    assert_eq!(
        external.headers.call_id(),
        Some("scall-1"),
        "response to the peer carries the peer's own call-id"
    );
    // Upstream mapping back to the real id works.
    assert_eq!(sbc.unmap_call_id(&hidden), Some(&"scall-1".to_string()));
    assert_eq!(sbc.tracked_calls(), 1);
}

#[test]
fn topology_hiding_resolves_both_directions_after_insert() {
    let mut sbc = Sbc::new(config());
    let req = invite("frank", "sip:frank@203.0.113.7:5060");

    // A→B: external request goes in with the peer's id, is relayed inward
    // with the hidden id.
    let relayed = match sbc.process_request(&req, PEER) {
        SbcAction::Relay(r) => r,
        _ => panic!("expected relay"),
    };
    let hidden = relayed.headers.call_id().unwrap().to_string();
    assert!(hidden.starts_with("h-"));
    assert_ne!(hidden, "scall-1");

    // B→A: an in-dialog response from the core (hidden id) resolves back to
    // the peer's id — the reverse map, not the forward map, is consulted.
    let core_resp =
        sip_core::builder::respond_to(&relayed, 183, "Session Progress", Vec::new(), None);
    let out = sbc.process_response(&core_resp);
    assert_eq!(out.headers.call_id(), Some("scall-1"));

    // And a provisional response later in the call resolves the same way
    // (insert happened once, lookups are repeatable).
    let core_200 = sip_core::builder::respond_to(&relayed, 200, "OK", Vec::new(), None);
    let out200 = sbc.process_response(&core_200);
    assert_eq!(out200.headers.call_id(), Some("scall-1"));
    assert_eq!(sbc.unmap_call_id(&hidden), Some(&"scall-1".to_string()));
}

#[test]
fn topology_hiding_leaves_external_ids_untouched_on_responses() {
    let mut sbc = Sbc::new(config());
    let req = invite("grace", "sip:grace@203.0.113.7:5060");
    let _ = sbc.process_request(&req, PEER);

    // Locally generated refusals are built from the peer's original request
    // and already carry the external id — they must pass through unchanged
    // (the reverse map has no entry for external ids).
    let refusal = sip_core::builder::respond_to(&req, 403, "Forbidden", Vec::new(), None);
    let screened = sbc.process_response(&refusal);
    assert_eq!(screened.headers.call_id(), Some("scall-1"));

    // Unknown call-ids pass through untouched as well.
    let mut unknown = req.clone();
    unknown.headers.remove_all("Call-ID");
    unknown.headers.add("Call-ID", "never-seen");
    let stray = sip_core::builder::respond_to(
        &unknown,
        481,
        "Call/Transaction Does Not Exist",
        Vec::new(),
        None,
    );
    assert_eq!(
        sbc.process_response(&stray).headers.call_id(),
        Some("never-seen")
    );
}

#[test]
fn non_hiding_mode_passes_headers_through() {
    let mut cfg = config();
    cfg.topology_hiding = false;
    let mut sbc = Sbc::new(cfg);
    let req = invite("erin", "sip:erin@10.0.0.1:5060");
    match sbc.process_request(&req, PEER) {
        SbcAction::Relay(relayed) => {
            assert_eq!(relayed.headers.call_id(), Some("scall-1"));
            assert!(relayed.headers.get("Contact").unwrap().contains("10.0.0.1"));
        }
        _ => panic!("expected relay"),
    }
}
