//! SBC behavior tests: ACL, rate limiting, NAT latching, topology hiding.

use sbc::{Acl, Cidr, Sbc, SbcAction, SbcConfig};
use sip_core::builder::RequestBuilder;
use sip_core::message::Method;
use sip_core::uri::{SipUri, TransportKind};
use std::net::{IpAddr, Ipv4Addr, SocketAddr};

const PEER: SocketAddr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(203, 0, 113, 7)), 5060);
const INTERNAL: SocketAddr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)), 5060);

fn invite(user: &str, contact: &str) -> sip_core::Request {
    RequestBuilder::new(
        Method::Invite,
        SipUri::parse(&format!("sip:{user}@example.com")).unwrap(),
    )
    .via(TransportKind::Udp, "peer.example:5060", Some("z9hG4bKs1"))
    .from(&format!("<sip:{user}@example.com>;tag=s1"))
    .to(&format!("<sip:{user}@example.com>"))
    .call_id(Some("scall-1"))
    .cseq(1)
    .contact(&format!("<{contact}>"))
    .build()
}

fn config() -> SbcConfig {
    SbcConfig {
        acl: Acl::default(),
        rate: sbc::RateLimit {
            per_second: 1000.0,
            burst: 1000.0,
        },
        external: "sbc.voip-stack:5060".into(),
        internal_target: INTERNAL,
        topology_hiding: true,
    }
}

#[test]
fn acl_allows_and_denies() {
    let mut sbc = Sbc::new(config());
    // Default: everything allowed.
    let req = invite("alice", "sip:alice@203.0.113.7:5060");
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Relay(_)
    ));

    // Deny the peer's subnet.
    let mut cfg = config();
    cfg.acl.deny = vec![Cidr::v4(203, 0, 113, 0, 24)];
    let mut sbc = Sbc::new(cfg);
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));

    // Allow-list that excludes the peer.
    let mut cfg = config();
    cfg.acl.allow = vec![Cidr::v4(198, 51, 100, 0, 24)];
    let mut sbc = Sbc::new(cfg);
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));
}

#[test]
fn cidr_matching() {
    let net = Cidr::v4(10, 0, 0, 0, 8);
    assert!(net.contains("10.1.2.3".parse().unwrap()));
    assert!(!net.contains("11.0.0.1".parse().unwrap()));
    let single = Cidr::v4(1, 2, 3, 4, 32);
    assert!(single.contains("1.2.3.4".parse().unwrap()));
    assert!(!single.contains("1.2.3.5".parse().unwrap()));
    let zero = Cidr::v4(0, 0, 0, 0, 0);
    assert!(zero.contains("255.255.255.255".parse().unwrap()));
}

#[test]
fn rate_limit_enforced() {
    let mut cfg = config();
    cfg.rate = sbc::RateLimit {
        per_second: 1.0,
        burst: 3.0,
    };
    let mut sbc = Sbc::new(cfg);
    let req = invite("bob", "sip:bob@203.0.113.7:5060");
    for _ in 0..3 {
        assert!(matches!(
            sbc.process_request(&req, PEER),
            SbcAction::Relay(_)
        ));
    }
    // Bucket drained.
    assert!(matches!(
        sbc.process_request(&req, PEER),
        SbcAction::Refuse(_)
    ));
}

#[test]
fn nat_latch_records_source() {
    let mut sbc = Sbc::new(config());
    let req = invite("carol", "sip:carol@203.0.113.7:5060");
    let _ = sbc.process_request(&req, PEER);
    let key = "sip:carol@203.0.113.7:5060";
    assert_eq!(sbc.latches().lookup(key), Some(PEER));
}

#[test]
fn topology_hiding_rewrites_call_id_and_contact() {
    let mut sbc = Sbc::new(config());
    let req = invite("dave", "sip:dave@10.0.0.1:5060");
    match sbc.process_request(&req, PEER) {
        SbcAction::Relay(relayed) => {
            let cid = relayed.headers.call_id().unwrap();
            assert!(cid.starts_with("h-"), "call-id hidden: {cid}");
            assert!(!cid.contains("scall-1"));
            let contact = relayed.headers.get("Contact").unwrap();
            assert!(
                contact.contains("sbc.voip-stack:5060"),
                "contact rewritten: {contact}"
            );
            assert!(!contact.contains("10.0.0.1"));
            // rport marking added for NAT traversal.
            let via = relayed.headers.first_via().unwrap();
            assert!(via.rport.is_some());
        }
        _ => panic!("expected relay"),
    }

    // A response generated by the internal core (carrying the REAL id)
    // leaves with the hidden id.
    let core_resp = sip_core::builder::respond_to(&req, 200, "OK", Vec::new(), None);
    let external = sbc.process_response(&core_resp);
    let cid = external.headers.call_id().unwrap();
    assert!(cid.starts_with("h-"), "response uses hidden id: {cid}");
    // Upstream mapping back to the real id works.
    assert_eq!(sbc.unmap_call_id(cid), Some(&"scall-1".to_string()));
    assert_eq!(sbc.tracked_calls(), 1);
}

#[test]
fn non_hiding_mode_passes_headers_through() {
    let mut cfg = config();
    cfg.topology_hiding = false;
    let mut sbc = Sbc::new(cfg);
    let req = invite("erin", "sip:erin@10.0.0.1:5060");
    match sbc.process_request(&req, PEER) {
        SbcAction::Relay(relayed) => {
            assert_eq!(relayed.headers.call_id(), Some("scall-1"));
            assert!(relayed.headers.get("Contact").unwrap().contains("10.0.0.1"));
        }
        _ => panic!("expected relay"),
    }
}
